# Project: core_of_creation
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = o_files/core.o o_files/librarian.o o_files/creator.o o_files/lua_worker.o o_files/renderer.o o_files/libraries.o o_files/ui_struct.o o_files/event_handler.o
LINKOBJ  = o_files/core.o o_files/librarian.o o_files/creator.o o_files/lua_worker.o o_files/renderer.o o_files/libraries.o o_files/ui_struct.o o_files/event_handler.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -L"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_image-2.6.0/x86_64-w64-mingw32/lib" -L"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_ttf-2.20.0/x86_64-w64-mingw32/lib" -L"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2-2.0.22/x86_64-w64-mingw32/lib" -static-libgcc -lmingw32  -lSDL2main  -lSDL2 -lSDL2_ttf -lSDL2_image C:/lua_bin/lua54.dll -pg -g3
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/json" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/lua_bin/include" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/LuaBridge-2.8/Source" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_ttf-2.20.0/x86_64-w64-mingw32/include/SDL2" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_image-2.6.0/x86_64-w64-mingw32/include/SDL2" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2-2.0.22/x86_64-w64-mingw32/include/SDL2"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/json" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/lua_bin/include" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/LuaBridge-2.8/Source" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_image-2.6.0/x86_64-w64-mingw32/include/SDL2" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2-2.0.22/x86_64-w64-mingw32/include/SDL2" -I"D:/CAVE/Programming/Projects/core_of_creation/using_libraries/sdl2/SDL2_ttf-2.20.0/x86_64-w64-mingw32/include/SDL2"
BIN      = build/core_of_creation.exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

o_files/core.o: core.cpp
	$(CPP) -c core.cpp -o o_files/core.o $(CXXFLAGS)

o_files/librarian.o: librarian.cpp
	$(CPP) -c librarian.cpp -o o_files/librarian.o $(CXXFLAGS)

o_files/creator.o: creator.cpp
	$(CPP) -c creator.cpp -o o_files/creator.o $(CXXFLAGS)

o_files/lua_worker.o: lua_worker.cpp
	$(CPP) -c lua_worker.cpp -o o_files/lua_worker.o $(CXXFLAGS)

o_files/renderer.o: renderer.cpp
	$(CPP) -c renderer.cpp -o o_files/renderer.o $(CXXFLAGS)

o_files/libraries.o: libraries.cpp
	$(CPP) -c libraries.cpp -o o_files/libraries.o $(CXXFLAGS)

o_files/ui_struct.o: ui_struct.cpp
	$(CPP) -c ui_struct.cpp -o o_files/ui_struct.o $(CXXFLAGS)

o_files/event_handler.o: event_handler.cpp
	$(CPP) -c event_handler.cpp -o o_files/event_handler.o $(CXXFLAGS)
